version: '3.8'

services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${PORT}:3001"
    container_name: lams-backend
    image: lams-backend-image
    restart: always
