version: '3.8'

networks:
  default:
    name: my_network

services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    container_name: lams-backend
    image: ${DOCKER_USERNAME}/lams-backend:latest
    restart: always
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
